### ISSUE TITLE
Add pages for local churches

### ISSUE THREAD

**Issue by reubenlillie** [pghnaz/pghnaz.org#2]
Should the metadata for local churches live in 11ty data files (cf. https://www.11ty.io/docs/data-global/)?

Is there a reason to create `.md` files for the individual church pages?

**Comment by reubenlillie** [comment]
The base data for local churches should live in individual JSON files inside the global `data` directory (cf. https://www.11ty.io/docs/data-global/).

If we choose to keep the “about” information to introduce more information about local churches, then that should be what we put in the content area of a `.md` file or other such template.

**Comment by reubenlillie** [comment]
#10 creates GeoJSON feature objects for each local church (cf. https://geojson.org/).

We still need to create page templates and `.md` files.

**Comment by czechju** [comment]
Update church naming for item.name

**Comment by czechju** [comment]
Add local service time in the church about section.

**Comment by reubenlillie** [comment]
@czechju, how do you think the `services` JSON object should be formatted?

**Comment by reubenlillie** [comment]
@czechju:

> Update church naming for item.name

After thinking things over, it makes better sense to keep the file names hyphenated like slugs. They’re URL slugs, not hashtags. It’s easier to read and catch typos with the hyphens. And the hyphens make it possible to split the file-slug strings with JavaScript if we ever find ourselves wanting to do that (e.g., target all churches with “community” in their name).

The only reason we were considering eliminating the hyphens in the first place was to maintain dot notation in JavaScript chaining rather than mixing in `Object[key]` references. We still have to use `Object[key]` notation, _but we would anyway_ in the templates to map over an array of all the churches or to target a particular local church. However, we should not have to hard code a specific church’s file slug in any of the templates.
