### ISSUE TITLE
Create homepage/main navigation

### ISSUE THREAD

**Issue by reubenlillie** [pghnaz/pghnaz.org#20]
The current site navigation mirrors http://nazarene.org/. 

- Who We Are
- Find A Church
- Organization
- Calendar
- Give
- News
- Contact Us

This is all well and good, but I’m inclined to follow a more modern story-board design approach using call-to-action prompts. The story-board should lead users on a journey, continuously calling them to a single action and inviting them to other actions along the way. The target user should be someone unfamiliar with our district or the Church of the Nazarene, but it should still make sense to someone who knows us better.

1. Make “Find a Church” the only call-to-action button/link in the top navigation for the homepage.

2. Then have a diptych inviting people to give (link to online giving form) or attend an event (link to  calendar); reiterate “Find a Church” for people to attend a service or other local church event near them or support a local ministry through giving.

3. Then have a triptych introducing people to our auxiliaries (SDMI, NMI, NMI); reiterate “Find a Church” for people to get involved locally.

4. Then have an at-a-glance introduction inviting people to meet our leaders (link to District Officers or District Organization) and check out our other district ministries (links to MCNC and PDCD); reiterate “Find a Church” for people to get involved in the unique ministry opportunities near them.

5. Tie the user and our people back to the mission (link to mission), vision (vision page?), and legacy (link to history?) of God’s work among us in western PA since 1898.

6. Then put a site-map-like inside navigation panes in the footer.

**Comment by czechju** [comment]
@reubenlillie  -- Rec'd feedback from Dan. Simplified layout using storyboard approach with an event driven home page is prefered. We'll have the find a church function in the top left as discussed. One asset we'll need to add for the individual churches is the service time. I'll add that as a separate issue to be tracked (and I'll own it).

**Comment by reubenlillie** [comment]
@czechju says I can close this.
